version: "3.8"

services:
  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - "8081:80"
    volumes:
      - ./html:/var/www/html
    environment:
      - MYSQL_PASS=password
    networks:
      - dvwa-net

networks:
  dvwa-net:
    driver: bridge
